### PR TITLE
feat(midway-bin): use async-await instead of generator

### PR DESCRIPTION
**Pull request by waitingsong**
##### Checklist

- [x] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change
使用 async-await 替代迭代器。

### CODE REVIEW

**Comment by waitingsong** [comment]
分支名好像写反了……

**Comment by waitingsong** [comment]
为啥 cov 下降这么多呢。

**Comment by czy88840616** [comment]
。。不明真相

**Comment by czy88840616** [comment]
image

**Comment by czy88840616** [comment]
可以单独跑看看

**Pull request merged**
