### PR TITLE
chore: update and add .editorconfig

### PR DESCRIPTION
**Pull request by waitingsong**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change
1. 对于 .md 文件增加 `max_line_length = off` 
2. 添加 `.editorconfig` 文件

### CODE REVIEW

**Comment by kurten** [comment]
感谢提mr，ci跑不通，能麻烦合并一下master然后再提mr么？

**Comment by waitingsong** [comment]
master 修复了？

**Comment by waitingsong** [comment]
@kurten  
pull 了没看到 master 有更新啊。

**Comment by waitingsong** [comment]
rebase master

**Pull request merged**
