### PR TITLE
feat: add project options in midway-bin

### PR DESCRIPTION
**Pull request by skmdev**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

midway-bin build

##### Description of change

To separate the tsconfig in production build and development, added a options in midway-bin build script

you can transpile the project with another tsconfig.json by using flag `-p` as below:
`midway-bin build -p [tsconfig path]`.

### CODE REVIEW

**Comment by czy88840616** [comment]
Great，i will merge this request and fix ci error later.

**Comment by czy88840616** [comment]
I found eslint error has be fixed in this mr ...

**Comment by skmdev** [comment]
thanks, hope this pr will appear on npm soon

**Comment by czy88840616** [comment]
release midway-bin@1.5.0

**Pull request merged**
