### PR TITLE
perf: decorator handler

### PR DESCRIPTION
**Pull request by czy88840616**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by waitingsong** [comment]
半羊，躺着，那个 PR 没时间弄～～

**Comment by czy88840616** [comment]
哪个？我都合了改完了。

**Comment by waitingsong** [comment]
就是 https://github.com/midwayjs/midway/pull/2540 这个。哈哈

**Comment by czy88840616** [comment]
已经合到这个分支，然后改了合到 main 进去了。

**Comment by waitingsong** [comment]
嗯嗯

**Pull request merged**
