### PR TITLE
fix(consul): Adjust the application registration logic to obtain consul instances when the application only acts as a service caller and does not register.

### PR DESCRIPTION
**Pull request by flyingCrp**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x ] commit message follows commit guidelines

##### Affected core subsystem(s)

consul组件的使用

##### Description of change

修复 [#1057]( https://github.com/midwayjs/midway/issues/1057)

### CODE REVIEW

**Comment by flyingCrp** [comment]
@czy88840616  可以帮忙看看吗? 很需要这个功能. 因为consul的实现有点老了. 所以我没做任何逻辑改动. 仅仅调整了`consul`对象的透传.  整个`consul`组件可能的话还是需要重构一下.按照新的规范和逻辑进行.非常感谢

**Comment by czy88840616** [comment]
先跑跑看，我不确定会不会有问题。

**Comment by czy88840616** [comment]
@midwayjs/consul@3.11.13

**Comment by flyingCrp** [comment]
我已经在业务层做了调整.先观察两天看看.有问题我会负责继续跟进和修复.

**Pull request merged**
