### PR TITLE
docs:fix  upload whitelist

### PR DESCRIPTION
**Pull request by yurenmu**
The whitelist cannot be null

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by echosoar** [comment]
为什么要删掉`配置为null` ？

**Comment by czy88840616** [comment]
应该是bug，这里文档其实没写错，是代码错了。

**Comment by waitingsong** [comment]
用 `false` 估计就不会让人产生混淆吧

**Comment by czy88840616** [comment]
是的

**Pull request closed without merging**
