### PR TITLE
feat(consul): register to consul server and lookup service with balancer

### PR DESCRIPTION
**Pull request by boostbob**
##### commit message

register to consul server and deregister when shutdown, but both are optional, also lookup the services which registered on the consul server, get the service instance with injected balancer, the origin consul object is managed by the IoC container also.

dependency:
- the hashicorp consul server(except unittest)  
- npm consul package  

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines
- [x] coding style check with mwts check (4 unused var warning )

---

##### How to use

```shell
npm i @midwayjs/consul -S
npm i @types/consul -D
```

###### Support

- [x] register (optional)
- [x] deregister on the shutdown (optional)
- [x] service balancer (default random)
- [x] expose the origin consul object

###### 1. import component firstly.

```
import * as consul from '@midwayjs/consul'

@Configuration({
  imports: [
    consul
  ],
  importConfigs: [join(__dirname, 'config')]
})
export class ContainerConfiguration {}
```

###### 2. config consul server and service definition.

```
consul: {
  provider: {
    // 注册本服务
    register: true,
    // 应用正常下线反注册
    deregister: true,
    // consul server 主机
    host: '192.168.0.10',
    // consul server 端口
    port: 8500,
    // 调用服务的策略(默认 random 具有随机性)
    strategy: 'random',
  },
  service: {
    address: '127.0.0.1',
    port: 7001,
    tags: ['tag1', 'tag2'],
    // others consul service definition
  }
}
```

###### 3. lookup the service instance to call.

```
// 1. 注入的方式
@Inject('consul:balancerService')
balancerService: IConsulBalancer;
// 2. 编码的方式
const balancerService = await app.getApplicationContext().getAsync<IConsulBalancer>('consul:balancerService');

// 查询的 service 数据是 consul 返回的原生数据，因为组件并不知道应用层使用了 consul 的哪些元数据信息
// 注意下 select 在没有服务实例时会抛出 Error

// 1. 查询通过健康检查的服务
const service = await balancerService.getBalancer().select('the-service-name');
// 2. 第二个参数设定 false 可能取到不健康的服务(不推荐)
const service = await balancerService.getBalancer().select('the-service-name', false);
```

###### 4. inject the origin consul object.

```
import * as Consul from 'consul';

// 使用 consul 官方包装的 API 接口
@Inject('consul:consul')
consul: Consul.Consul;
```

### CODE REVIEW

**Comment by czy88840616** [comment]
看起来差不多了，不需要再改了吧。

**Comment by boostbob** [comment]
后面想支持多服务器注册，因为生产环境一般 service 会同时注册到多个 client 类型的 consul 服务器上，打算放在 1.0.1 版本，你看合适吗?

**Comment by czy88840616** [comment]
额，放在 midway 主库里的版本就跟着主库升级啦 😸，现在是2.9.x了，不需要关心版本了。。

**Comment by czy88840616** [comment]
急用么？急的话我可以放到 2.9.x 里。

**Comment by boostbob** [comment]
不急用，我现在直接放项目里的，深入学习 core 中。

**Pull request merged**
